# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARuke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARuke
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire','4.5.1'
  pod 'SwiftyJSON', '3.1.4'


  target 'ARukeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARukeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

  plugin 'cocoapods-keys', {
  :project => "ARuke",
  :keys => [
    "GoogleMapAPIKey"
    ]}
